import { MediaCandidate, ScriptScene } from '../types';
import { config } from '../config';

// Pika 2.2 text-to-video generation service
// Uses FAL AI's Pika model via @fal-ai/client

interface PikaGenerationOptions {
  prompt: string;
  duration?: '5' | '10';
  resolution?: '720p' | '1080p';
  seed?: number;
}

interface PikaVideoResult {
  url: string;
  width?: number;
  height?: number;
  duration?: number;
}

interface PikaResult {
  video?: PikaVideoResult;
  seed: number;
  requestId: string;
  data?: {
    video?: PikaVideoResult;
    seed?: number;
  };
}

/**
 * Generate a video from text description using Pika 2.2
 */
export const generateVideo = async (
  options: PikaGenerationOptions
): Promise<PikaResult> => {
  const { fal } = await import('@fal-ai/client');
  
  // Configure FAL client with API key
  if (config.falKey) {
    fal.config({ credentials: config.falKey });
  }

  const result = await fal.subscribe('fal-ai/pika/v2.2/text-to-video', {
    input: {
      prompt: options.prompt,
      duration: options.duration || '5',
      resolution: options.resolution || '720p',
      ...(options.seed ? { seed: options.seed } : {})
    },
    logs: true,
    onQueueUpdate: (update) => {
      if (update.status === 'IN_PROGRESS') {
        update.logs.map((log) => log.message).forEach(console.log);
      }
    },
  });

  // Handle the response - FAL returns data directly
  const responseData = result as unknown as {
    data?: {
      video?: {
        url: string;
        width?: number;
        height?: number;
        duration?: number;
      };
      seed?: number;
    };
    requestId: string;
  };

  return {
    video: responseData.data?.video ? {
      url: responseData.data.video.url,
      width: responseData.data.video.width || 576,
      height: responseData.data.video.height || 1024,
      duration: responseData.data.video.duration || 5
    } : undefined,
    seed: responseData.data?.seed || 0,
    requestId: responseData.requestId,
    data: responseData.data
  };
};

/**
 * Find scene media using Pika text-to-video
 * This replaces Pexels stock video search with AI-generated videos
 */
export const findSceneMedia = async (
  scene: ScriptScene,
  productCategory: string,
  description: string
): Promise<MediaCandidate[]> => {
  if (!config.falKey) {
    console.warn('FAL_KEY not configured - Pika video generation disabled');
    return [];
  }

  try {
    // Build a rich prompt from scene data
    const prompt = buildPikaPrompt(scene, productCategory, description);
    
    console.log('Generating video with Pika 2.2:', prompt.substring(0, 100) + '...');
    
    const result = await generateVideo({
      prompt,
      duration: '5',
      resolution: '720p',
    });

    if (!result.video) {
      console.warn('Pika generation returned no video');
      return [];
    }

    return [{
      kind: 'video',
      source: 'pika',
      externalId: result.requestId,
      url: result.video.url,
      width: result.video.width || 576,
      height: result.video.height || 1024,
      duration: result.video.duration || 5,
      attribution: 'Generated by Pika AI (fal.ai)',
      query: prompt
    }];
  } catch (error) {
    console.error('Pika video generation failed:', error);
    return [];
  }
};

/**
 * Build an optimized prompt for Pika 2.2
 */
function buildPikaPrompt(
  scene: ScriptScene,
  productCategory: string,
  description: string
): string {
  const parts: string[] = [];

  // Add headline
  if (scene.headline) {
    parts.push(scene.headline);
  }

  // Add visual description
  if (scene.visualBrief) {
    parts.push(scene.visualBrief);
  }

  // Add product context
  if (productCategory) {
    parts.push(productCategory);
  }

  // Add description
  if (description) {
    parts.push(description);
  }

  // Add style keywords for better results
  parts.push('cinematic, high quality, professional');

  return parts.join(', ');
}

/**
 * Check if Pika service is configured
 */
export const isPikaConfigured = (): boolean => {
  return !!config.falKey;
};